# -*- coding: utf-8 -*-
"""ICAFS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QDehEfaA1B0fH-dhaW4XPOTwYWSaZ4c
"""

!pip install testflows.combinatorics

from testflows.combinatorics import Covering
paramter_to_test = {"1":[0,1],"2":[0,1],"3":[0,1],"4":[0,1],"5":[0,1],"6":[0,1]}
generate_covering_array = Covering(paramter_to_test, strength=3)
print(generate_covering_array)

import random
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

center = (0.5, 0.5)
radius = 0.5
circle = Circle(center, radius)

fig, ax = plt.subplots()
ax.add_patch(circle)
ax.set_aspect('equal')

lst = []
points_outside = 0
points_inside = 0

while(points_inside < 1000 ):
  x  = random.uniform(0, 1)
  y  = random.uniform(0, 1)
  a  = random.uniform(0, .1)
  b  = random.uniform(0, .2)
  c =  random.uniform(0, .3)
  d =  random.uniform(0, .4)

  if (x - center[0])**2 + (y - center[1])**2  <=  radius**2:
        lst.append([x,y,a,b,c,d,1])
        plt.plot(x,y,'ro')
        points_inside+=1

while(points_outside < 1000 ):
  x  = random.uniform(0, 1)
  y  = random.uniform(0, 1)
  a  = random.uniform(0, .1)
  b  = random.uniform(0, .2)
  c =  random.uniform(0, .3)
  d =  random.uniform(0, .4)

  if (x - center[0])**2 + (y - center[1])**2  >  radius**2:
        lst.append([x,y,a,b,c,d,0])
        plt.plot(x,y,'bo')
        points_outside+=1

#plt.savefig('/content/save_data/circle_in_the_sqaure.png', dpi=300, transparent=False, bbox_inches='tight')
plt.show()

import pandas as pd
cisDf = pd.DataFrame(lst, columns=['X', 'Y','A','B','C','D','Result'])
#df =  df.sample(frac = 1)

X_cis = cisDf[['X', 'Y','A','B','C','D']]
y_cis= cisDf[['Result']]
X_cis

import pandas as pd
import numpy as np

df = pd.read_csv('/content/sample_data/cacao.csv')
df_x = df.iloc[:, 1:]

y_cacao = df.iloc[:, 0:1]
X_cacao = (df_x-df_x.min())/(df_x.max()-df_x.min())

from math import inf
from testflows.combinatorics import Covering
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn import svm
import random
from sklearn.neighbors import KNeighborsClassifier


def ICAFS(datasetX, datasetY, strenght,max_iteartion):
  max_iteartion_aux =  max_iteartion
  t_strenght = strenght
  v_variable = [0, 1]
  best_f1_score = float('-inf')
  best_data_set = datasetX.columns.values.copy()
  max_iteration = 60
  max_len = inf
  score_list = []
  featur_list = []
  iter_list = []
  max_it = 0;

  while (max_iteartion_aux >= 0):

      dict_parameters = {}
      partial_best_list = []
      partial_score = 0
      for colum_key in best_data_set:
          dict_parameters[colum_key] = v_variable
      random.shuffle(best_data_set)
      generate_covering_array = Covering(dict_parameters, strength=t_strenght)
      for test in generate_covering_array.array:
          list_attributes_to_consider = []

          check_for_all_cero = True
          for (test_key, test_value) in test.items():
              if test_value == 1:
                  check_for_all_cero = False
                  list_attributes_to_consider.append(test_key)

          if check_for_all_cero:
              continue
          df_temp = datasetX.loc[ :,list_attributes_to_consider]
          X_train_temp, X_test_temp, y_train_temp, y_test_temp = train_test_split(df_temp, datasetY.values.ravel(), test_size=0.20,
                                                                                  random_state=42)

          #stdsc = StandardScaler()
          #X_train_std = stdsc.fit_transform(X_train_temp)
          #X_test_std = stdsc.transform(X_test_temp)
          clf_new = svm.SVC()
          clf_new.fit(X_train_temp, y_train_temp)

          y_pred = clf_new.predict(X_test_temp)
          print(list_attributes_to_consider)
          score = f1_score(y_test_temp, y_pred,average='macro')
          #print(score)
          if score > partial_score :
              partial_score = score
              partial_best_list = list_attributes_to_consider
          clf_new = None
      best_data_set = partial_best_list.copy()
      best_f1_score = partial_score
      print("best_f1_score= %s" % best_f1_score)
      print(best_data_set)
      print(len(best_data_set))
      print('---------------------')

      aux_data_score = best_f1_score
      score_list.append(aux_data_score)
      max_iteartion_aux = max_iteartion_aux-1
      max_it = max_it +1
      featur_list.append(len(best_data_set))
      iter_list.append(max_it)
  return score_list,featur_list,iter_list

score_cacao,festure_cacao,iter_cacao = ICAFS(X_cacao, y_cacao, 2,20)

import matplotlib.pyplot as plt
import numpy as np
import math

fig, (ax1, ax2) = plt.subplots(1, 2)
ax1.set_title("Features/Iteration")
ax1.bar(iter_cacao, festure_cacao, color = "red")

ax2.set_title("Scores/Iteration")
ax2.bar(iter_cacao, score_cacao, color = "red")
#plt.savefig('/content/saveimage/icafs_cacao.png', bbox_inches='tight')

from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

clf_aux =  KNeighborsClassifier(n_neighbors=2)
scores = cross_val_score(clf_aux, X[['2150', '2277', '2386', '2460']], y.values.ravel(), cv=5)
scores

score_cis,festure_cis,iter_cis = ICAFS(X_cis, y_cis, 3,4)

import matplotlib.pyplot as plt
import numpy as np
import math

fig, (ax1, ax2) = plt.subplots(1, 2)
ax1.set_title("Features/Iteration")
ax1.bar(iter_cis, festure_cis, color = "red")

ax2.set_title("Scores/Iteration")
ax2.bar(iter_cis, score_cis, color = "red")
#plt.savefig('/content/saveimage/icafs_cis.png', bbox_inches='tight')

alagarrobo = pd.read_csv('/content/sample_data/algarrobo.csv')
algarrobo_x = alagarrobo.loc[:, 'R':'REDVI']
y_algarrobo = alagarrobo['Labels'].replace(to_replace=['N', 'P'], value=[0, 1])
algarrobo_x['B']

algarrobo_x['B']

X_algarrono = (algarrobo_x-algarrobo_x.min())/(algarrobo_x.max()-algarrobo_x.min())
algarrobo_x['B']

from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

clf_aux =  KNeighborsClassifier(n_neighbors=3)
scores = cross_val_score(clf_aux, X_algarrono, y_algarrobo.values.ravel(), cv=5)
print(scores.mean())

X_train_complete, X_test_complete, y_train_complete, y_test_complete = train_test_split(X_algarrono, y_algarrobo, test_size=0.2, random_state=42)

from sklearn import svm
scv_clf_complete = svm.SVC(C=1,kernel='poly',degree=5)
scv_clf_complete.fit(X_train_complete, y_train_complete)

#scores = cross_val_score(scv_clf, X_train_complete, y_train_complete, cv=5)
#print(scores.mean())
accuracy_score(y_test_complete, scv_clf_complete.predict(X_test_complete))

score_algarrobo,festure_algarrobo,iter_algarrobo = ICAFS(X_algarrono,y_algarrobo,3,max_iteartion=20)

import matplotlib.pyplot as plt
import numpy as np
import math

fig, (ax1, ax2) = plt.subplots(1, 2)
ax1.set_title("Features/Iteration")
ax1.bar(iter_algarrobo, festure_algarrobo, color = "red")

ax2.set_title("Scores/Iteration")
ax2.bar(iter_algarrobo, score_algarrobo, color = "red")

"""**UMAP vizualization**"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install umap-learn

import umap
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

umap_2d = umap.UMAP(n_components=2)
umap_3d = umap.UMAP(n_components=3)

X_reduced_algarrobo =  X_algarrono[['R', 'EXGR', 'MGRVI', 'EVI']]
X_reduced_algarrobo

X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = train_test_split(X_reduced_algarrobo, y_algarrobo.values, test_size=0.2, random_state=42)

from sklearn import svm
#scv_clf = svm.SVC(C=1,kernel='poly',degree=5)
#scv_clf.fit(X_train_reduced, y_train_reduced)

knn_reduced =  KNeighborsClassifier(n_neighbors=3)
knn_reduced.fit(X_train_reduced,y_train_reduced)
f1_score(y_test_reduced, knn_reduced.predict(X_test_reduced),average='macro')

#scores = cross_val_score(clf_aux, X_algarrono, y_algarrobo.values.ravel(), cv=5)

#scores = cross_val_score(scv_clf, X_train_reduced, y_train_reduced, cv=5)
#print(scores.mean())
#scores

#897
#143
for i in range(2000,4000):
  scv_clf = svm.SVC(C=i)
  scv_clf.fit(X_train_reduced, y_train_reduced)
  score = f1_score(y_test_reduced, scv_clf.predict(X_test_reduced),average='macro')
  print(str(i) + "-" + str(score))

from sklearn.metrics import accuracy_score
accuracy_score(y_test_reduced, scv_clf.predict(X_test_reduced))

X_reduced_standarized = StandardScaler().fit_transform(X_reduced_algarrobo)

algarrobo_umap_2d = umap_2d.fit_transform(X_reduced_standarized)
algarrobo_umap_3d = umap_3d.fit_transform(X_reduced_standarized)

import plotly.express as px

plt.scatter(
    algarrobo_umap_2d[:, 0],
    algarrobo_umap_2d[:, 1],
    c=[sns.color_palette()[x] for x in alagarrobo.Labels.map({"N":0, "P":1})])

plt.gca().set_aspect('equal', 'datalim')
plt.title('UMAP Algarrobo', fontsize=24);

fig_3d = px.scatter_3d(
    algarrobo_umap_3d, x=0, y=1, z=2,
    color=alagarrobo.Labels, labels={'color': 'species'}
)
fig_3d.update_traces(marker_size=5)
fig_3d.show()

"""# **Cacao Experiment**"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install umap-learn

import umap
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import plotly.express as px

#['1735', '1926', '2031']
#'1736', '1993', '2089'
cacao_reduced = X_cacao[['1736', '1993', '2089']]
cacao_reduced

X_reduced_cacao_standarized = StandardScaler().fit_transform(cacao_reduced)

fig_3d = px.scatter_3d(
    X_reduced_cacao_standarized, x=0, y=1, z=2,
    color=df['10101010.00'], labels={'color': 'species'}
)
fig_3d.update_traces(marker_size=5)
fig_3d.show()

X_train_reduced_cacao, X_test_reduced_cacao, y_train_reduced_caco, y_test_reduced_cacao = train_test_split(cacao_reduced, y_cacao, test_size=0.2, random_state=42)

knn_reduced =  KNeighborsClassifier(n_neighbors=3)
knn_reduced.fit(X_train_reduced_cacao,y_train_reduced_caco)
f1_score(y_test_reduced_cacao, knn_reduced.predict(X_test_reduced_cacao),average='macro')

cacao_umap_2d = umap_2d.fit_transform(X_reduced_cacao_standarized)
cacao_umap_3d = umap_3d.fit_transform(X_reduced_cacao_standarized)

plt.scatter(
    cacao_umap_2d[:, 0],
    cacao_umap_2d[:, 1],
    c=[sns.color_palette()[x] for x in y_cacao['10101010.00'] .map({ 1 : 0, 2 :1 , 3 :2, 4 :3, 5 :4, 6 :5 })])

plt.gca().set_aspect('equal', 'datalim')
plt.title('PCA Algarrobo', fontsize=24);

fig_3d = px.scatter_3d(
    cacao_umap_3d, x=0, y=1, z=2,
    color=df['10101010.00'], labels={'color': 'species'}
)
fig_3d.update_traces(marker_size=5)
fig_3d.show()